Update development-server.yml

diff --git a/.github/workflows/development-server.yml b/.github/workflows/development-server.yml
--- a/.github/workflows/development-server.yml
+++ b/.github/workflows/development-server.yml
@@ -35,7 +35,25 @@ jobs:
         cd ./client
         npm install --legacy-peer-deps
 
-    - name: Build and Start Server
+    - name: Start Server
       run: |
         dotnet watch -p ./API &
         npm start --prefix ./client
+        sleep 5
+
+    - name: Check Server Status
+      run: |
+        if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+        elif [ "$RUNNER_OS" == "Windows" ]; then
+          response_code=$(curl -s -o NUL -w "%{http_code}" http://localhost:3000)
+        else
+          echo "Unsupported operating system"
+          exit 1
+        fi
+        if [ "$response_code" == "200" ]; then
+          echo "Server is running successfully"
+        else
+          echo "Server failed to start or is not responding"
+          exit 1
+        fi
