Update development-server.yml

diff --git a/.github/workflows/development-server.yml b/.github/workflows/development-server.yml
--- a/.github/workflows/development-server.yml
+++ b/.github/workflows/development-server.yml
@@ -39,30 +39,39 @@ jobs:
       run: |
         dotnet watch --project ./API &
         sleep 5
-
-    - name: Wait for Server to Start
+        
+    - name: Check if dotnet watch is running
       run: |
-        while ! nc -z localhost 5000; do sleep 1; done
-        echo "good"
-        if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
-          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
-          echo "$response_code"
-        elif [ "$RUNNER_OS" == "Windows" ]; then
-          response_code=$(curl -s -o NUL -w "%{http_code}" http://localhost:5000)
-          echo "$response_code"
+        if pgrep -x "dotnet" > /dev/null; then
+          echo "dotnet watch is running"
         else
-          echo "Unsupported operating system"
+          echo "dotnet watch is not running"
           exit 1
         fi
+        
+    # - name: Wait for Server to Start
+    #   run: |
+    #     while ! nc -z localhost 5000; do sleep 1; done
+    #     echo "good"
+    #     if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
+    #       response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
+    #       echo "$response_code"
+    #     elif [ "$RUNNER_OS" == "Windows" ]; then
+    #       response_code=$(curl -s -o NUL -w "%{http_code}" http://localhost:5000)
+    #       echo "$response_code"
+    #     else
+    #       echo "Unsupported operating system"
+    #       exit 1
+    #     fi
 
-        # Check the response code
-        if [ "$response_code" == "200" ]; then
-          echo "Server is running successfully"
-          pkill -f "dotnet watch"
-        else
-          echo "Server failed to start or is not responding"
-          exit 1
-        fi
+    #     # Check the response code
+    #     if [ "$response_code" == "200" ]; then
+    #       echo "Server is running successfully"
+    #       pkill -f "dotnet watch"
+    #     else
+    #       echo "Server failed to start or is not responding"
+    #       exit 1
+    #     fi
         
 
     # - name: Check Server Status
